apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: wingtiptoysregistrynab.azurecr.io/demo:latest  # or use the specific tag you push in your GitHub Actions
        ports:
        - containerPort: 8080
      imagePullSecrets:  # Add this section
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo
